### PR TITLE
[HOPSWORKS-1405] Resolve IP of Consul domain name if enabled for MStorageDescriptor location URI

### PR DESCRIPTION
**Pull request by kouzant**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405

### CODE REVIEW

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Sorry my bad. I forgot to tell you, but Hive sometimes also uses SQL directly against the database, without using the ORM. There are some locations there to be fixed as well: https://github.com/logicalclocks/hive/blob/master/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java

**Comment by kouzant** [comment]
@SirOibaf updated my PR with fixes in `MetaStoreDirectSql`

**Pull request merged**
