### PR TITLE
[HOPSWORKS-1695] update hops to hadoop3

### PR DESCRIPTION
**Pull request by berthoug**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1695

### CODE REVIEW

**Comment by SirOibaf** [comment]
PR looks ok, I'm working on getting https://github.com/logicalclocks/hive/pull/9 first in - which also bumps the version of Hive.

**Comment by berthoug** [comment]
I should probably also update the version number as it breack compatibility with hadoop2.
Should we put it on the same as #9 or should I update on more?

**Comment by SirOibaf** [comment]
Hive 3 is supposed to be compatible with Hadoop 3. When I cherry-picked the JIRAs for Hive 3 I did the reverse of what you have done now.
Also Hive 4 is actually going to be released and so we can't increase the first number, so I'd just increment the latest digit. 

I think @kouzant's PR is almost ready to merge - I just had a classpath issue I need to resolve.

**Comment by SirOibaf** [comment]
Hive 3 is supposed to be compatible with Hadoop 3. When I cherry-picked the JIRAs for Hive 3 I did the reverse of what you have done now.
Also Hive 4 is actually going to be released and so we can't increase the first number, so I'd just increment the latest digit. 

I think @kouzant's PR is almost ready to merge - I just had a classpath issue I need to resolve.

**Comment by berthoug** [comment]
Ok, we can see what version number we put when the other PR is merged.

**Pull request merged**
